Merged PR 60337: Implement chart version validation and container build validation for PRs
With this PR I am implementing the following to the PR validation pipeline:
 - a validation for the helm charts versions
 - a validation for the container build that would fail if an error were detected in the run

diff --git a/pipelines/pr.yml b/pipelines/pr.yml
--- a/pipelines/pr.yml
+++ b/pipelines/pr.yml
@@ -98,6 +98,56 @@ steps:
       NX_BASE: $(targetBranch)
 
   - bash: |
+      set -o errexit
+      set -o pipefail
+      echo "Recreating affected artifacts ${NX_HEAD} -> ${NX_BASE}..."
+      affected=$(npx nx show projects --affected --exclude 'api-mock-*,lib-*,tool-*')
+      echo "The affected apps are: ${affected}"
+      for project in ${affected}
+      do
+        npx nx container $project
+      done
+    displayName: Validate container build
+    env:
+      NX_HEAD: $(sourceBranch)
+      NX_BASE: $(targetBranch)
+
+  - task: AzureCLI@2
+    name: validateChartsVersion
+    displayName: Validate charts version
+    inputs:
+      azureSubscription: ${{ parameters.serviceConnection }}
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        updatedCharts=$(
+          git diff --name-only $(sourceBranch) $(targetBranch) -R -- \
+            | grep -Po "(?<=^charts\/)[a-z-]+(?=\/)" \
+            | uniq
+        )
+        for project in ${updatedCharts}
+        do
+          response=$(az acr repository show-tags \
+            --repository charts/wts/${project} \
+            --orderby time_desc \
+            --top 1
+          )
+          tag=$(echo $response | jq -r .[])
+          latestSemVer=$(echo $tag | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
+          chartPath="charts/${project}/Chart.yaml"
+          chartVersion=$(grep '^version:' $chartPath | awk '{print $2}')
+          echo "Latest Helm chart version from ACR for ${project}: ${latestSemVer}"
+          echo "Chart.yaml version for ${project}: ${chartVersion}"
+          if [ "$latestSemVer" == "$chartVersion" ]; then
+            echo "ERROR: Chart version $chartVersion for project $project already exists in ACR. Please update Chart.yaml file to reflect the new changes."
+            echo "##vso[task.logissue type=error]Chart version $chartVersion for project $project already exists in ACR. Please update Chart.yaml file to reflect the new changes."
+            exit 1
+          fi
+        done
+    env:
+      AZURE_DEFAULTS_ACR: ${{ parameters.containerRegistryName }}
+
+  - bash: |
       if ! npx nx format:check --all; then
         MSG='Some file are improperly formatted. See logs for a list.'
         echo "##vso[task.logissue type=error]$MSG"
